server:
  port: 9091
dubbo:
  application:
    name: site-service-boot-provider
  registry:
    address: zookeeper://127.0.0.1:2184,127.0.0.1:2185,127.0.0.1:2186
  protocol:
    name: dubbo
    port: 20882

